SELECT TRACK.*, GROUP_CONCAT(ARTIST.name) AS artists
FROM
    TRACK
    JOIN ARTIST_TRACK ON TRACK.id = ARTIST_TRACK.track_id
    JOIN ARTIST ON ARTIST_TRACK.artist_id = ARTIST.id
WHERE
    TRACK.id IN (:ids)
GROUP BY
    TRACK.id;